name: CI Pipeline

on:
  push:
    branches:
      - develop
  workflow_dispatch:

  pull_request:
    branches: [ main ]

jobs:
  build-test-and-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python -m unittest test_weather.py

    - name: Build Docker image
      run: |
        docker build -t your-dockerhub-username/weather-app:${{ env.ENV }} .

    - name: Log in to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

    - name: Push Docker image
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push your-dockerhub-username/weather-app:${{ env.ENV }}

    - name: Run Flake8 Linter
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Set Environment
      run: |
        if [ "${{ github.ref }}" == "refs/heads/develop" ]; then
          echo "ENV=dev" >> $GITHUB_ENV
        else
          echo "ENV=prod" >> $GITHUB_ENV
        fi